logger:
  default: warning
  logs:
    custom_components.victoriametrics: debug

# Loads default set of integrations. Do not remove.
default_config:

victoriametrics:
  url: http://admin:1234@localhost:8428

